python /home/mike/.vscode-oss/extensions/ms-python.python-2020.10.332292344/pythonFiles/testing_tools/run_adapter.py discover pytest -- --rootdir /home/mike/scrap/mypy -s --cache-clear .
Test Discovery failed: 
Error: Traceback (most recent call last):
  File "/home/mike/.vscode-oss/extensions/ms-python.python-2020.10.332292344/pythonFiles/testing_tools/run_adapter.py", line 17, in <module>
    from testing_tools.adapter.__main__ import parse_args, main
  File "/home/mike/.vscode-oss/extensions/ms-python.python-2020.10.332292344/pythonFiles/testing_tools/adapter/__main__.py", line 9, in <module>
    from . import pytest, report
  File "/home/mike/.vscode-oss/extensions/ms-python.python-2020.10.332292344/pythonFiles/testing_tools/adapter/pytest/__init__.py", line 7, in <module>
    from ._discovery import discover
  File "/home/mike/.vscode-oss/extensions/ms-python.python-2020.10.332292344/pythonFiles/testing_tools/adapter/pytest/_discovery.py", line 8, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'

python /home/mike/.vscode-oss/extensions/ms-python.python-2020.10.332292344/pythonFiles/testing_tools/run_adapter.py discover pytest -- --rootdir /home/mike/scrap/mypy -s --cache-clear .
python /home/mike/.vscode-oss/extensions/ms-python.python-2020.10.332292344/pythonFiles/testing_tools/run_adapter.py discover pytest -- --rootdir /home/mike/scrap/mypy -s .
